2022/12/30 17:24:58 [error] 280#280: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/"
2022/12/30 17:25:00 [error] 280#280: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/login"
2022/12/30 17:25:01 [error] 280#280: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "POST /api/tokens HTTP/1.1", upstream: "http://127.0.0.1:3000/tokens", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/login"
2022/12/30 19:47:36 [error] 485#485: *1176 upstream prematurely closed connection while reading response header from upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/nginx/certificates/test-http?domains=%5B%22atled-robotics.com%22%5D HTTP/1.1", upstream: "http://127.0.0.1:3000/nginx/certificates/test-http?domains=%5B%22atled-robotics.com%22%5D", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/certificates"
2022/12/30 19:47:38 [error] 485#485: *1176 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/proxy"
2022/12/30 19:47:46 [error] 513#513: *1181 upstream prematurely closed connection while reading response header from upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/nginx/certificates/test-http?domains=%5B%22atled-robotics.com%22%5D HTTP/1.1", upstream: "http://127.0.0.1:3000/nginx/certificates/test-http?domains=%5B%22atled-robotics.com%22%5D", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/certificates"
2022/12/30 19:47:48 [error] 513#513: *1181 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/certificates"
2022/12/30 19:52:30 [error] 541#541: *1184 upstream prematurely closed connection while reading response header from upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/nginx/certificates/test-http?domains=%5B%22atled-robotics.com%22%5D HTTP/1.1", upstream: "http://127.0.0.1:3000/nginx/certificates/test-http?domains=%5B%22atled-robotics.com%22%5D", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/certificates"
2022/12/30 19:52:31 [error] 541#541: *1184 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/proxy"
2022/12/30 19:52:34 [error] 541#541: *1184 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/proxy"
2022/12/30 20:18:09 [error] 281#281: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/proxy"
2022/12/30 20:18:14 [error] 281#281: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/nginx/proxy"
2022/12/30 20:57:26 [error] 282#282: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 192.168.18.3, server: nginxproxymanager, request: "GET /api/ HTTP/1.1", upstream: "http://127.0.0.1:3000/", host: "192.168.18.9:81", referrer: "http://192.168.18.9:81/"
2022/12/30 21:09:27 [warn] 229#229: conflicting server name "atled-technologies.com" on 0.0.0.0:80, ignored
2022/12/30 21:09:27 [warn] 229#229: conflicting server name "atled-technologies.com" on [::]:80, ignored
2022/12/30 21:09:37 [warn] 229#229: conflicting server name "atled-technologies.com" on 0.0.0.0:80, ignored
2022/12/30 21:09:37 [warn] 229#229: conflicting server name "atled-technologies.com" on [::]:80, ignored
2022/12/30 21:13:32 [warn] 229#229: conflicting server name "atled-technologies.com" on 0.0.0.0:80, ignored
2022/12/30 21:13:32 [warn] 229#229: conflicting server name "atled-technologies.com" on [::]:80, ignored
2022/12/30 21:13:42 [warn] 229#229: conflicting server name "atled-technologies.com" on 0.0.0.0:80, ignored
2022/12/30 21:13:42 [warn] 229#229: conflicting server name "atled-technologies.com" on [::]:80, ignored
